feedback

diff --git a/Scripts/TestAll b/Scripts/TestAll
--- a/Scripts/TestAll
+++ b/Scripts/TestAll
@@ -12,10 +12,16 @@ swift build -c release \
 release=$(swift build -c release --show-bin-path)
 
 if ! bash -c '"$1" > /dev/null 2>&1' -- "${release}/AssertTestsOn" > /dev/null 2>&1; then
-    echo "AssertTestsOn passed"
+    echo 'AssertTestsOn passed'
+else
+    echo 'AssertTestsOn failed'
+    exit 1
 fi
 if  bash -c '"$1" > /dev/null 2>&1' -- "${release}/AssertTestsOff" > /dev/null 2>&1; then
-    echo "AssertTestsOff passed"
+    echo 'AssertTestsOff passed'
+else
+    echo 'AssertTestsOff failed'
+    exit 1
 fi
 
 swift test -c release \
